### ISSUE TITLE
Yap-6.3.3 not working on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by stanoevboris** [xflows/rdm#7]
I tried compiling the given source code for [YAP](https://github.com/xflows/rdm/blob/master/yap-6.3.3/yap-6.3.3.zip). 
But there is an issue arising while trying to execute the "make" command.
This is happening for python-rdm==0.3.6.

 gcc -O3 -fomit-frame-pointer -Wall -Wstrict-prototypes -Wmissing-prototypes -g -O2 -DMYDDAS_ODBC -DCOROUTINING=1 -DCUT_C=1 -DRATIONAL_TREES=1 -DDEPTH_LIMIT=1 -DTABLING=1 -DHAVE_CONFIG_H -D_YAP_NOT_INSTALLED_=1 -I. -I../H -I../include  -I../os -I../OPTYap -I../BEAM -I../MYDDAS -rdynamic  -Lcustom_path/yap-6.3.3/yap-6.3.3/arch -Wl,-R/usr/local/lib -Wl,-R,/usr/local/lib/Yap -o yap yap.o libYap.a -lodbc -lgmp -lreadline -lncurses -lresolv -lcrypt -lstdc++ -lm  -ldl -lnsl
/usr/bin/ld: libYap.a(pl-error.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-file.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-files.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-fmt.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-glob.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-option.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-os.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-privitf.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-prologflag.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-read.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-rl.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-string.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-table.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-tai.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-text.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-write.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-yap.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-codelist.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-ctype.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
/usr/bin/ld: libYap.a(pl-dtoa.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: multiple definition of `ATOM_'; libYap.a(pl-buffer.o):custom_path/yap-6.3.3/yap-6.3.3/arch/../H/pl-yap.h:230: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:728: yap] Error 1

**Comment by vpodpecan** [comment]
Likely your GCC is too new and refuses to compile YAP. YAP is notoriously hard to compile and I had troubles finding a version that works (6.3.3). There is absolutely no chance for fixing YAP to work on Ubuntu 22.04.

If you are OK with using python-rdm in a Docker container, I recommend using Debian Stretch (9) and python 3.7. Then you can use the following Dockerfile snippet to install YAP and python-rdm:

```dockerfile
FROM python:3.7-stretch
RUN apt-get update && \
    apt-get install -y build-essential cmake wget && \
    cd .. && \
    wget https://github.com/xflows/rdm/raw/master/yap-6.3.3/yap-6.3.3.zip && \
    unzip yap-6.3.3 && \
    cd yap-6.3.3/ && \
    mkdir arch && cd arch && \
    export CXXFLAGS=-fpermissive && ../configure --enable-tabling=yes --with-readline=no && \
    make && \
    make install
RUN pip install python-rdm==0.3.6
```
